import dwarf from './img/dwarf-removebg.png'

const clans = [
    {
        id: 1,
        cardType: "clash-card barbarian",
        cssImgDiv: "clash-card__image clash-card__image--barbarian",
        img: "https://s3-us-west-2.amazonaws.com/s.cdpn.io/195612/barbarian.png",
        imgAlt: "barbarian",
        csslevel: "clash-card__level clash-card__level--barbarian",
        level: "Level 4",
        cssName: "clash-card__unit-name",
        name: "The Barbarian",
        cssDes: "clash-card__unit-description",
        Descrpt: "The Barbarian is a kilt-clad Scottish warrior with an angry, battle-ready expression, hungry for destruction. He has Killer yellow horseshoe mustache.",
        cssCardRow: "clash-card__unit-stats clash-card__unit-stats--barbarian clearfix",
        num: "20",
        numSup: "S",
        text: "Training",
        num1: "16",
        numSup1: "",
        text1: "Speed",
        cssnoborder: "no-border",
        num2: "150",
        numSup2: "",
        text2: "Cost"
    },
    {
        id: 2,
        cardType: "clash-card archer",
        cssImgDiv: "clash-card__image clash-card__image--archer",
        img: "https://s3-us-west-2.amazonaws.com/s.cdpn.io/195612/archer.png",
        imgAlt: "archer",
        csslevel: "clash-card__level clash-card__level--archer",
        level: "Level 5",
        cssName: "clash-card__unit-name",
        name: "The Archer",
        cssDes: "clash-card__unit-description",
        Descrpt: "The Archer is a female warrior with sharp eyes. She wears a short, light green dress, a hooded cape, a leather belt and an attached small pouch.",
        cssCardRow: "clash-card__unit-stats clash-card__unit-stats--archer clearfix",
        num: "25",
        numSup: "5",
        text: "Training",
        num1: "24",
        numSup1: "",
        text1: "Speed",
        cssnoborder: "no-border",
        num2: "300",
        numSup2: "",
        text2: "Cost"
    },
    {
        id: 3,
        cardType: "clash-card giant",
        cssImgDiv: "clash-card__image clash-card__image--giant",
        img: "https://s3-us-west-2.amazonaws.com/s.cdpn.io/195612/giant.png",
        imgAlt: "giant",
        csslevel: "clash-card__level clash-card__level--giant",
        level: "Level 5",
        cssName: "clash-card__unit-name",
        name: "The Giant",
        cssDes: "clash-card__unit-description",
        Descrpt: "Slow, steady and powerful, Giants are massive warriors that soak up huge amounts of damage. Show them a turret or cannon and you'll see their fury unleashed!",
        cssCardRow: "clash-card__unit-stats clash-card__unit-stats--giant clearfix",
        num: "2",
        numSup: "M",
        text: "Training",
        num1: "12",
        numSup1: "",
        text1: "Speed",
        cssnoborder: "no-border",
        num2: "2250",
        numSup2: "",
        text2: "Cost"
    },
    {
        id: 4,
        cardType: "clash-card goblin",
        cssImgDiv: "clash-card__image clash-card__image--goblin",
        img: "https://s3-us-west-2.amazonaws.com/s.cdpn.io/195612/goblin.png",
        imgAlt: "goblin",
        csslevel: "clash-card__level clash-card__level--goblin",
        level: "Level 5",
        cssName: "clash-card__unit-name",
        name: "Level 5",
        cssDes: "clash-card__unit-description",
        Descrpt: "These pesky little creatures only have eyes for one thing: LOOT! They are faster than a Spring Trap, and their hunger for resources is limitless.",
        cssCardRow: "clash-card__unit-stats clash-card__unit-stats--goblin clearfix",
        num: "30",
        numSup: "S",
        text: "Training",
        num1: "32",
        numSup1: "",
        text1: "Speed",
        cssnoborder: "no-border",
        num2: "100",
        numSup2: "",
        text2: "Cost"
    },
    {
        id: 5,
        cardType: "clash-card wizard",
        cssImgDiv: "clash-card__image clash-card__image--wizard",
        img: "https://s3-us-west-2.amazonaws.com/s.cdpn.io/195612/wizard.png",
        imgAlt: "wizard",
        csslevel: "clash-card__level clash-card__level--wizard",
        level: "Level 6",
        cssName: "clash-card__unit-name",
        name: "The Wizard",
        cssDes: "clash-card__unit-description",
        Descrpt: "The Wizard is a terrifying presence on the battlefield. Pair him up with some of his fellows and cast concentrated blasts of destruction on anything, land or sky!",
        cssCardRow: "clash-card__unit-stats clash-card__unit-stats--wizard clearfix",
        num: "5",
        numSup: "M",
        text: "Training",
        num1: "16",
        numSup1: "",
        text1: "Speed",
        cssnoborder: "no-border",
        num2: "4000",
        numSup2: "",
        text2: "Cost"
    },
    {
        id: 6,
        cardType: "clash-card wizard",
        cssImgDiv: "clash-card__image clash-card__image--warrior",
        img: dwarf,
        imgAlt: "warrior dwarf",
        csslevel: "clash-card__level clash-card__level--wizard",
        level: "Level 8",
        cssName: "clash-card__unit-name",
        name: "The warrior Dwarf",
        cssDes: "clash-card__unit-description",
        Descrpt: "The warrior Dwarf is a terrifying presence on the battlefield. Pair him up with some of his fellows and cast concentrated blasts of destruction on anything, land or sky!",
        cssCardRow: "clash-card__unit-stats clash-card__unit-stats--wizard clearfix",
        num: "5",
        numSup: "M",
        text: "Training",
        num1: "16",
        numSup1: "",
        text1: "Speed",
        cssnoborder: "no-border",
        num2: "4000",
        numSup2: "",
        text2: "Cost"
    }
];

export default clans;